### PR TITLE
Add first handfull of exercises

### PR DESCRIPTION
**Pull request by ozan**
This PR adds 6 exercises (tests and examples). I want to make sure the way we have these set up suits the CI setup.

Refs #4 

@kytrinyx what do we need to do to get the examples running against the tests on CI? An individual test can be run on the command line like e.g.:

```sh
java -jar /path/to/mars.jar nc leap/runner.mips leap/example.mips
```

and will exit 0 or 1 for success or failure respectively. It will also write either a success message or a brief error message to stdout.

The CI machine will need Java J2SE 1.5 (or later) SDK and a copy of mars.jar available [here](http://courses.missouristate.edu/KenVollmar/mars/download.htm).

@quackingduck FYI the only changes here from our internal version are that I've changed the test cases to largely match those in the other exercism tracks, and I've commented out the include of the implementation from the runner, so that "example.mips" can be run from the CLI in CI. Users who prefer the GUI can just uncomment the include line as needed.

### CODE REVIEW

**Comment by kytrinyx** [comment]
For some exercises we have canonical data sets for the tests, in the JSON files in https://github.com/exercism/x-common. This page should have all the useful links: http://exercism.io/languages/mips/contribute

I think CI needs a script that it can run which will return zero or non-zero for the entire set of exercises. Perhaps a Makefile of some sort which could run individual tests? I think that's what we do in PHP and JavaScript and a couple of other languages.

https://github.com/exercism/xphp/blob/master/Makefile

**Comment by ozan** [comment]
> For some exercises we have canonical data sets for the tests, in the JSON files in https://github.com/exercism/x-common.

Great! Yes I've been trying to follow those where I can.

> I think CI needs a script that it can run which will return zero or non-zero for the entire set of exercises. Perhaps a Makefile of some sort which could run individual tests?

Oh oops I see the travis.yml now. I can take care of it, thanks :)

**Comment by ozan** [comment]
OK RAD, we now have CI testing the tests against the examples. Gonna merge this and close #4

**Comment by kytrinyx** [comment]
Y'all are FAST! :heart:

**Pull request merged**
